### ISSUE TITLE
Repeatable MoarVM crash

### ISSUE THREAD

**Issue by lizmat** [japhb/Terminal-LineEditor#7]
Steps to reproduce on M1:

- install [`REPL` 0.0.9](https://raku.land/zef:lizmat/REPL?v=0.0.9), which also installs a `repl` CLI
- install `Terminal LineEditor`

Then start up the `repl` CLI, and enter: `say ²³⁴⁴/₇;`

The result for me is:
```
% repl                            
To exit type 'exit' or '^D'
[0] > say ²³⁴⁴/₇;                                                                                
5119416553549266766988439498442158349992332565107770365485689373631524276983225018013434270335101978916.571429
[0] >rakudo(75019,0x1ec19cc00) malloc: Heap corruption detected, free list is damaged at 0x6000027e4080
*** Incorrect guard value: 18433
rakudo(75019,0x1ec19cc00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      repl
```
The values `18433` and `0x1ec19cc00` are always the same.

**Comment by lizmat** [comment]
Turns out this was caused by the fact that Termios on MacOS is larger than on Linux (ispeed and ospeed are 64bit, rather than 32bit).

A fix in https://raku.land/zef:patrickb/Terminal-MakeRaw will fix this: @patrickbkr

**Comment by patrickbkr** [comment]
I plan to replace Terminal-MakeRaw with [Terminal-API](https://git.sr.ht/~patrickb/Terminal-API/tree/main/item/lib/Terminal/API.rakumod). The T-MR API is locked in to the Termios API, so it can't ever do Windows. T-A tries to provide an OS agnostic API.
T-A has the MacOS fix applied already. I just need to get the Windows implementation working to be sure that the API actually works out. It'll probably take a week or two.

@lizmat: Do you think it's worthwhile to backport the changes to T-MR to have a fix for the meantime?

**Comment by lizmat** [comment]
> Do you think it's worthwhile to backport the changes to T-MR to have a fix for the meantime?

Depends on how long T-A is going to take?

**Comment by patrickbkr** [comment]
> > Do you think it's worthwhile to backport the changes to T-MR to have a fix for the meantime?
> 
> Depends on how long T-A is going to take?

> It'll probably take a week or two.
